spring:
  application:
    name: hecate
server:
  port: 8080
springdoc:
  show-actuator: true
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: '/actuator'
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when-authorized
    env:
      show-values: when-authorized
    configprops:
      show-values: when-authorized
    shutdown:
      enabled: false

hecate:
  telegramSendPhotoUrl: "https://api.telegram.org/bot%s/sendPhoto"