name: maven-test
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
jobs:
  maven-test:
    name: maven-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        java-package: jdk
        architecture: x64
        distribution: 'temurin'
        cache: 'maven'
    - run: mvn -B clean verify
    - name: Upload JaCoCo coverage report
      if: github.ref_type == 'branch' && github.ref_name == 'dev'
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: target/site/jacoco/